server {
    listen 80;
    server_name ceexp.nu-tf-lab.jp;

    client_max_body_size 50M;

    location /static/ {
        alias /home/ceexpii/scoring_system/staticfiles/;
        access_log off;
        expires 7d;
    }

    location /media/ {
        alias /home/ceexpii/scoring_system/media/;
        expires 1d;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/run/scoring-system/scoring-system.sock;
        proxy_read_timeout 300;
    }
}
