# Generated by Django 5.2.1 on 2025-05-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0003_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('topic', models.CharField(max_length=100)),
                ('teacher', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
