# Generated by Django 5.2.1 on 2025-05-22 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0005_submission_date_submission_experiment_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='graded_file',
            field=models.FileField(blank=True, null=True, upload_to='graded_submissions/', verbose_name='添削ファイル'),
        ),
        migrations.AddField(
            model_name='submission',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='得点'),
        ),
        migrations.CreateModel(
            name='GradingChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100, verbose_name='チェック項目名')),
                ('checked', models.BooleanField(default=False, verbose_name='チェック済み')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='submission.submission')),
            ],
        ),
    ]
