# Generated by Django 5.2.1 on 2025-05-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0007_submission_experiment_number_submission_report_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('pre', '予習レポート'), ('main', '本レポート')], max_length=10)),
                ('label', models.CharField(max_length=32)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'order'],
            },
        ),
    ]
