# Generated by Django 5.2.1 on 2025-05-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0008_scoringitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoringitem',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
    ]
