# Generated by Django 5.2.1 on 2025-05-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0009_scoringitem_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='score',
        ),
        migrations.AddField(
            model_name='submission',
            name='score_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
