# Generated by Django 5.2.1 on 2025-05-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0011_experimentcompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
