# Generated by Django 5.2.1 on 2025-06-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0013_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
