# Generated by Django 5.2.1 on 2025-06-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0014_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='teacher',
            field=models.CharField(max_length=100),
        ),
    ]
