# Generated by Django 5.2.1 on 2025-06-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0015_alter_schedule_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='teacher',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
