# Generated by Django 5.2.1 on 2025-06-13 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0018_userprofile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("teacher", "Teacher"),
                    ("admin", "Admin"),
                    ("non-editing teacher", "Non-editing Teacher"),
                ],
                default="student",
                max_length=20,
            ),
        ),
    ]
