# Generated by Django 5.2.1 on 2025-06-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0019_alter_userprofile_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="final_evaluated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="submission",
            name="final_score",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
