# Generated by Django 5.2.1 on 2025-12-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0023_alter_enrollment_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='role',
            field=models.CharField(choices=[('student', 'student'), ('teacher', 'teacher'), ('non-editing teacher', 'non-editing teacher'), ('admin', 'admin')], max_length=20),
        ),
    ]
