# Generated by Django 5.2.1 on 2025-12-20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0032_experimentcompletion_course_offering'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoringitem',
            name='course_offering',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='scoring_items',
                to='submission.courseoffering',
            ),
        ),
    ]
