# Generated by Django 5.2.1 on 2025-12-22 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0033_scoringitem_course_offering'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoringitem',
            name='code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='scoringitem',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scoring_items_common', to='submission.course'),
        ),
        migrations.AddField(
            model_name='scoringitem',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scoringitem',
            name='show_in_grading_form',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='role',
            field=models.CharField(choices=[('student', 'student'), ('teacher', 'teacher'), ('course-teacher', 'course-teacher'), ('non-editing teacher', 'non-editing teacher'), ('admin', 'admin')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('course-teacher', 'Course Teacher'), ('admin', 'Admin'), ('non-editing teacher', 'Non-editing Teacher')], default='student', max_length=20),
        ),
    ]
