# Generated by GPT-5 on 2025-12-22

from django.db import migrations


SYSTEM_DEFS = [
    {"code": "late", "label": "遅刻", "category": "pre"},
    {"code": "late", "label": "遅刻", "category": "main"},
    {"code": "absence", "label": "欠席", "category": "main"},
    {"code": "lab_time", "label": "実験時間", "category": "pre"},
]


def forwards(apps, schema_editor):
    ScoringItem = apps.get_model("submission", "ScoringItem")
    Course = apps.get_model("submission", "Course")

    # 1) course_offering があるものは course を補完
    for item in ScoringItem.objects.filter(course__isnull=True, course_offering__isnull=False):
        item.course_id = item.course_offering.course_id
        item.save(update_fields=["course"])

    # 2) 旧「全体共通」を各科目共通へ複製し、旧データは削除
    common_items = list(
        ScoringItem.objects.filter(course__isnull=True, course_offering__isnull=True)
    )
    courses = list(Course.objects.all())
    if common_items and courses:
        for item in common_items:
            for course in courses:
                ScoringItem.objects.create(
                    course_id=course.id,
                    course_offering_id=None,
                    category=item.category,
                    label=item.label,
                    code=item.code,
                    is_system=item.is_system,
                    show_in_grading_form=item.show_in_grading_form,
                    order=item.order,
                    weight=item.weight,
                )
        for item in common_items:
            item.delete()

    # 3) 既存ラベルに code/is_system を付与
    ScoringItem.objects.filter(label="遅刻").update(
        code="late", is_system=True, show_in_grading_form=False
    )
    ScoringItem.objects.filter(label="欠席").update(
        code="absence", is_system=True, show_in_grading_form=False
    )
    ScoringItem.objects.filter(label="実験時間").update(
        code="lab_time", is_system=True, show_in_grading_form=False
    )

    # 4) 各科目共通にシステム項目を必ず作成
    for course in Course.objects.all():
        for definition in SYSTEM_DEFS:
            code = definition["code"]
            category = definition["category"]
            label = definition["label"]
            existing = ScoringItem.objects.filter(
                course_id=course.id,
                course_offering__isnull=True,
                category=category,
                code=code,
            ).first()
            if existing:
                continue
            by_label = ScoringItem.objects.filter(
                course_id=course.id,
                course_offering__isnull=True,
                category=category,
                label=label,
            ).first()
            if by_label:
                by_label.code = code
                by_label.is_system = True
                by_label.show_in_grading_form = False
                by_label.save(update_fields=["code", "is_system", "show_in_grading_form"])
                continue
            ScoringItem.objects.create(
                course_id=course.id,
                course_offering_id=None,
                category=category,
                label=label,
                code=code,
                is_system=True,
                show_in_grading_form=False,
                order=0,
                weight=0,
            )


def backwards(apps, schema_editor):
    # No-op: 元の「全体共通」を復元しない
    return


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0034_scoringitem_code_scoringitem_course_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
