# Generated by Django 5.2.1 on 2026-03-03 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0036_merge_0033_course_experiment_groups_0035_scoringitem_course_common_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment_number', models.CharField(max_length=32)),
                ('task_no', models.CharField(max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiment_progresses', to='submission.courseoffering')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiment_progresses', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_experiment_progresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['course_offering', 'experiment_number'], name='submission__course__0f8872_idx'), models.Index(fields=['student', 'course_offering', 'experiment_number'], name='submission__student_47bbb3_idx')],
                'unique_together': {('student', 'course_offering', 'experiment_number', 'task_no')},
            },
        ),
        migrations.CreateModel(
            name='ExperimentTaskConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment_number', models.CharField(max_length=32)),
                ('task_list', models.JSONField(blank=True, default=list)),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiment_task_configs', to='submission.courseoffering')),
            ],
            options={
                'unique_together': {('course_offering', 'experiment_number')},
            },
        ),
    ]
