# Generated by Django 5.2.1 on 2026-03-05 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0037_experimentprogress_experimenttaskconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionTextIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_version', models.CharField(default='v1', max_length=16)),
                ('file_hash', models.CharField(blank=True, default='', max_length=64)),
                ('file_size', models.BigIntegerField(default=0)),
                ('file_mtime', models.FloatField(default=0)),
                ('normalized_text', models.TextField(blank=True, default='')),
                ('sections_json', models.JSONField(blank=True, default=list)),
                ('signature_json', models.JSONField(blank=True, default=list)),
                ('indexed_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='text_index', to='submission.submission')),
            ],
        ),
        migrations.CreateModel(
            name='SimilarityJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm_version', models.CharField(default='v1', max_length=32)),
                ('status', models.CharField(choices=[('queued', 'queued'), ('running', 'running'), ('done', 'done'), ('failed', 'failed')], default='queued', max_length=12)),
                ('result_cache_json', models.JSONField(blank=True, default=dict)),
                ('checked_count', models.PositiveIntegerField(default=0)),
                ('displayed_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_jobs', to='submission.submission')),
            ],
            options={
                'unique_together': {('target_submission', 'algorithm_version')},
            },
        ),
    ]
