# Generated by Django 5.2.1 on 2026-03-09 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0038_submissiontextindex_similarityjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentEquipmentCheckLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateField()),
                ('experiment_number', models.CharField(max_length=32)),
                ('phase', models.CharField(choices=[('start', 'start'), ('end', 'end')], max_length=8)),
                ('checked_items_json', models.JSONField(blank=True, default=list)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiment_equipment_check_logs', to=settings.AUTH_USER_MODEL)),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiment_equipment_check_logs', to='submission.courseoffering')),
            ],
            options={
                'indexes': [models.Index(fields=['course_offering', 'schedule_date', 'phase', 'checked_at'], name='submission__course__81d4d1_idx'), models.Index(fields=['course_offering', 'schedule_date', 'experiment_number'], name='submission__course__f8c193_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExperimentEquipmentCheckState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateField()),
                ('experiment_number', models.CharField(max_length=32)),
                ('phase', models.CharField(choices=[('start', 'start'), ('end', 'end')], max_length=8)),
                ('checked_items_json', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiment_equipment_check_states', to='submission.courseoffering')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_experiment_equipment_check_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['course_offering', 'schedule_date', 'phase'], name='submission__course__4e6958_idx'), models.Index(fields=['course_offering', 'schedule_date', 'experiment_number', 'phase'], name='submission__course__844ae4_idx')],
                'unique_together': {('course_offering', 'schedule_date', 'experiment_number', 'phase')},
            },
        ),
        migrations.CreateModel(
            name='ExperimentEquipmentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment_number', models.CharField(max_length=32)),
                ('items_json', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiment_equipment_configs', to='submission.courseoffering')),
            ],
            options={
                'indexes': [models.Index(fields=['course_offering', 'experiment_number'], name='submission__course__31859c_idx')],
                'unique_together': {('course_offering', 'experiment_number')},
            },
        ),
    ]
