# Generated by Django 5.2.1 on 2026-04-14 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0040_discussionbonus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalRubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment_number', models.CharField(max_length=32)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_rubrics', to='submission.courseoffering')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_final_rubrics', to=settings.AUTH_USER_MODEL)),
                ('source_rubric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_rubrics', to='submission.finalrubric')),
            ],
            options={
                'ordering': ['course_offering', 'experiment_number', '-version'],
                'unique_together': {('course_offering', 'experiment_number', 'version')},
            },
        ),
        migrations.CreateModel(
            name='FinalRubricCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('max_points', models.PositiveIntegerField(default=5)),
                ('order', models.PositiveIntegerField(default=0)),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='submission.finalrubric')),
                ('source_criterion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_criteria', to='submission.finalrubriccriterion')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FinalRubricOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('points', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='submission.finalrubriccriterion')),
                ('source_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_options', to='submission.finalrubricoption')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FinalRubricScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='submission.finalrubric')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_rubric_score', to='submission.submission')),
            ],
        ),
        migrations.CreateModel(
            name='FinalRubricScoreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='score_items', to='submission.finalrubriccriterion')),
                ('rubric_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='submission.finalrubricscore')),
                ('selected_option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='score_items', to='submission.finalrubricoption')),
            ],
            options={
                'ordering': ['criterion__order', 'id'],
                'unique_together': {('rubric_score', 'criterion')},
            },
        ),
    ]
