# Generated by Codex on 2026-04-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0041_finalrubric_finalrubriccriterion_finalrubricoption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalrubric',
            name='scope',
            field=models.CharField(
                choices=[('default', 'デフォルト'), ('offering', '年度個別')],
                default='offering',
                max_length=16,
            ),
        ),
        migrations.AlterModelOptions(
            name='finalrubric',
            options={'ordering': ['course_offering', 'scope', 'experiment_number', '-version']},
        ),
        migrations.AlterUniqueTogether(
            name='finalrubric',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='finalrubric',
            constraint=models.UniqueConstraint(
                fields=('course_offering', 'experiment_number', 'scope', 'version'),
                name='uniq_final_rubric_scope_version',
            ),
        ),
        migrations.AddConstraint(
            model_name='finalrubric',
            constraint=models.UniqueConstraint(
                condition=models.Q(is_active=True),
                fields=('course_offering', 'experiment_number', 'scope'),
                name='uniq_active_final_rubric_per_scope',
            ),
        ),
    ]
