# Generated by Codex on 2026-04-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0042_finalrubric_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalrubricscore',
            name='adjustment_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
