# Generated by Django 5.2.1 on 2026-05-21 11:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def copy_stamp_text_to_layout(apps, schema_editor):
    Stamp = apps.get_model('submission', 'Stamp')
    for stamp in Stamp.objects.all():
        if not stamp.layout_text:
            stamp.layout_text = stamp.text
            stamp.save(update_fields=['layout_text'])


def clear_stamp_layout(apps, schema_editor):
    Stamp = apps.get_model('submission', 'Stamp')
    Stamp.objects.update(layout_text='')


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0043_finalrubricscore_adjustment_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stamp',
            options={'ordering': ['created_at', 'id']},
        ),
        migrations.AddField(
            model_name='stamp',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='stamp',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stamps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stamp',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stamp',
            name='layout_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stamp',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='stamp',
            name='text',
            field=models.CharField(max_length=64),
        ),
        migrations.RunPython(copy_stamp_text_to_layout, clear_stamp_layout),
        migrations.CreateModel(
            name='StampCaseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=40)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stamp_case_sections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StampCaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('stamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_items', to='submission.stamp')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='submission.stampcasesection')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
