# Generated by Django 5.2.1 on 2026-06-17 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0044_alter_stamp_options_stamp_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningContentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment_number', models.CharField(blank=True, max_length=32)),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120)),
                ('summary', models.TextField(blank=True)),
                ('layout_mode', models.CharField(choices=[('section', 'セクション')], default='section', max_length=24)),
                ('layout_json', models.JSONField(blank=True, default=dict)),
                ('is_published', models.BooleanField(default=False)),
                ('publish_start_at', models.DateTimeField(blank=True, null=True)),
                ('publish_end_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_content_pages', to='submission.courseoffering')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_learning_content_pages', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_learning_content_pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['course_offering', 'experiment_number', 'title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LearningContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('section', 'セクション'), ('text', 'テキスト'), ('link', 'リンク'), ('table', '表'), ('tabs', 'タブ')], default='link', max_length=16)),
                ('content_type', models.CharField(blank=True, choices=[('', 'なし'), ('pdf', 'PDF'), ('mp4', 'MP4'), ('link', 'リンク')], default='', max_length=16)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('body', models.TextField(blank=True)),
                ('external_url', models.URLField(blank=True, max_length=1000)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='submission.learningcontentblock')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='submission.learningcontentpage')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LearningContentAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer_email', models.EmailField(blank=True, max_length=255)),
                ('viewer_domain', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(choices=[('page_view', 'ページ閲覧'), ('content_open', 'コンテンツを開く')], max_length=24)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='submission.learningcontentblock')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='submission.learningcontentpage')),
            ],
            options={
                'ordering': ['-accessed_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='learningcontentpage',
            index=models.Index(fields=['course_offering', 'experiment_number'], name='submission__course__c0cc31_idx'),
        ),
        migrations.AddIndex(
            model_name='learningcontentpage',
            index=models.Index(fields=['is_published', 'publish_start_at', 'publish_end_at'], name='submission__is_publ_a6e5c5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='learningcontentpage',
            unique_together={('course_offering', 'slug')},
        ),
        migrations.AddIndex(
            model_name='learningcontentblock',
            index=models.Index(fields=['page', 'parent', 'display_order'], name='submission__page_id_5413ad_idx'),
        ),
        migrations.AddIndex(
            model_name='learningcontentblock',
            index=models.Index(fields=['content_type'], name='submission__content_8f80c7_idx'),
        ),
        migrations.AddIndex(
            model_name='learningcontentaccesslog',
            index=models.Index(fields=['page', 'action', 'accessed_at'], name='submission__page_id_d52080_idx'),
        ),
        migrations.AddIndex(
            model_name='learningcontentaccesslog',
            index=models.Index(fields=['viewer_email', 'accessed_at'], name='submission__viewer__6c3d60_idx'),
        ),
    ]
