# Generated by Django 5.2.1 on 2026-06-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0045_learningcontentpage_learningcontentblock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningcontentblock',
            name='block_type',
            field=models.CharField(choices=[('text_media', 'テキストおよびメディア領域'), ('section', 'セクション'), ('text', 'テキスト'), ('link', 'リンク'), ('table', '表'), ('tabs', 'タブ')], default='link', max_length=16),
        ),
    ]
