# Generated by Django 5.2.1 on 2025-12-20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('submission', '0032_experimentcompletion_course_offering'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='course_offering',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='attendance_records',
                to='submission.courseoffering',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('user', 'date', 'course_offering')},
        ),
    ]
