# Generated by Django 5.2.1 on 2026-03-31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendanceforgetrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentHelpTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment_group', models.CharField(max_length=16)),
                ('experiment_number', models.CharField(max_length=32)),
                ('request_type', models.CharField(choices=[('call', '呼び出し'), ('question', '質問')], max_length=16)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', '未対応'), ('in_progress', '対応中'), ('resolved', '対応済み')], default='pending', max_length=16)),
                ('student_read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiment_help_tickets', to='submission.courseoffering')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_experiment_help_tickets', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiment_help_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
